#!/bin/bash

set -eu pipefail

git worktree list \
  | grep -v "\(bare\)" \
  | fzf-tmux -p \
    --with-nth 1,3 \
    --pointer=' ' \
    --preview-window down \
    --preview "git l --color=always -n10 {2}" \
  | awk '{print $1}'

