-- These daemons are props to elenapan.
-- https://github.com/elenapan/dotfiles
-- require("demons.battery")
-- require("demons.volume")
-- require("demons.brightness")
-- require("demons.ram")
-- require("demons.cpu")
-- require("demons.temp")
-- require("demons.disk")
-- require("demons.weather")
