#!/bin/zsh

alias v="nvim"
alias aqua="Asciiquarium"
alias cat="bat --paging=never"

alias mux="tmux"
alias muxk="tmux kill-server"
alias muxa="tmux a"

# Task warrior tooling
alias t="task"
alias tap="task context personal"
alias taw="task context work"
alias tw="timew"
alias chore="task add +personal +chore" 
alias bce="$EDITOR $HOME/Documents/Notes/journal.beancount"
alias de="cd ~/Documents/Notes"
alias gb="cd ~/Documents/GenesisBlock"

# Elixir Goodies
alias m="iex -S mix"
alias ms="iex -S mix phx.server"
alias mdg="mix deps.get"
alias mdc="mix deps.clean --all"

# use exa for ls
alias ls='exa -a --icons --color=always --group-directories-first'
alias la='exa -al --icons --color=always --group-directories-first'
alias ll='exa -l --icons --color=always --group-directories-first'
alias lt='exa -aT --icons --color=always --group-directories-first'

