#! /bin/sh

setup-monitors &
picom --experimental-backends &
dunst -conf ~/.config/dunst/dunstrc &
~/.config/polybar/launch.sh &
sxhkd ~/.config/bspwm/bspwm-sxhkdrc &
hsetroot -solid "#1e1c31"

monitor_count=$(monitor-count)

case $monitor_count in
  1)
    bspc monitor 1 2 3 4 5 6 7 8 9
  ;;
  2)
    bspc monitor 'DisplayPort-0' -d 1 2 3 4
    bspc monitor 'DisplayPort-1' -d 5 6 7
  ;;
  3)
    bspc monitor 'DisplayPort-0' -d 1 2 3 4
    bspc monitor 'DisplayPort-1' -d 5 6 7
    bspc monitor 'HDMI-A-0' -d 8 9
esac

bspc config border_width        1
bspc config normal_border_color  "#585273"
bspc config focused_border_color "#87DFEB"
bspc config window_gap          12
bspc config top_padding         42

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer      true

bspc rule -a kitty desktop='1'
bspc rule -a kitty-tasks desktop='8' locked=true
bspc rule -a kitty-monitor state=floating
bspc rule -a firefox desktop='2'
bspc rule -a zoom desktop='2' follow=on
bspc rule -a nitrogen manage=off
bspc rule -a Lxappearance 							follow=on		state=floating
bspc rule -a discord desktop='3'
bspc rule -a Slack desktop='3'
bspc rule -a Mailspring desktop='4'
bspc rule -a Minetime desktop='8'
bspc rule -a kitty-scratch sticky=true hidden=true

mailspring &
discord &
slack &
firefox &
kitty &
kitty --listen-on=unix:/tmp/kitty-scratch --class kitty-scratch --config ~/.config/kitty/kitty-scratch.conf --hold --directory=$HOME &
nextcloud &
kitty --listen-on=unix:/tmp/kitty-tasks --class kitty-tasks --hold &

sleep 5
bspc desktop '5' -f
flatpak run com.spotify.Client &
sleep 3

bspc desktop '8' -f
minetime &
sleep 5

kitty @ --to=unix:/tmp/kitty-scratch send_text "v ~/Documents/knowledge/\r"

bspc desktop '1' -f
