#! /bin/sh

sxhkd &
picom &
dunst -conf ~/.config/dunst/dunstrc &
hsetroot -solid "#1e1c31" &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        1
bspc config normal_border_color  "#3E3859"
bspc config focused_border_color "#63F2F1"
bspc config window_gap          12
bspc config top_padding         42

bspc config automatic_scheme alternate
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer      true

bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a zoom desktop='^5' follow=on
bspc rule -a nitrogen manage=off
bspc rule -a Lxappearance 							follow=on		state=floating
bspc rule -a discord desktop='^3'
bspc rule -a Slack desktop='^3'
bspc rule -a Mailspring desktop='^5'

# Launch windows where selector is not working
bspc desktop '^4' -f
spotify &
sleep 2

mailspring &
discord &
slack &
firefox &
kitty &
nextcloud &

