# ░█▀▀░█░░░█▀█░█▀▄░█▀█░█░░░░░▀▀█░█░█░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀
# ░█░█░█░░░█░█░█▀▄░█▀█░█░░░░░▄▀░░█▀▄░░░█░░░█░█░█░█░█▀▀░░█░░█░█
# ░▀▀▀░▀▀▀░▀▀▀░▀▀░░▀░▀░▀▀▀░░░▀▀▀░▀░▀░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀
# Configuration shared across all zk notebooks

[note]

language = "en"

id-charset = "alphanum"
id-length = 8
id-case = "lower"
filename = "{{id}}-{{slug title}}"
extension = "md"
template = "default.md"

[extra]
author = "Stephen"

[format.markdown]
hashtags = false
colon-tags = true
link-format = "markdown"

# EXTERNAL TOOLS
[tool]

editor = "nvim"
pager = "bat"
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
today = "--sort created- --created 'today'"
complete = "--tag complete"
active = "--tag active"
idea = "--tag idea"
project = "--tag Project"

[alias]
e = 'zk edit --interactive $@'
links = 'zk list --format link --no-pager --quiet --delimiter="\n" $@'
projects = 'zk e project $@'
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'

[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "none"
# Warn for dead links between notes.
dead-link = "warning"
