# Global zk settings
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 4

# Letter case for the random IDs.
id-case = "lower"

# EXTRA VARIABLES
[extra]
author = "Stephen"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Pager used to scroll through long output.
pager = "bat"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
## Journal aliases
journal = 'zk --notebook-dir ~/Documents/Wolf $@'
day = 'zk new --group day --no-input --notebook-dir ~/Documents/Wolf journal'
week = 'zk new --group week --no-input --notebook-dir ~/Documents/Wolf journal'
quarter = 'zk new --group quarter --no-input --notebook-dir ~/Documents/Wolf journal'
year = 'zk new --group year --no-input --notebook-dir ~/Documents/Wolf journal'

## Working aliases
meeting = 'zk new --group meeting --title $1 --notebook-dir ~/Documents/Warrior/genesis-block meetings'

## Knowledge aliases
zettel = 'zk --notebook-dir ~/Documents/Wanderer $@'
ls = 'zk list --notebook-dir ~/Documents/Wanderer $@'
lookup = 'zk edit --interactive --notebook-dir ~/Documents/Wanderer $@'

