# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

if [ ! -f $HOME/.work-zshrc ]; then
  echo "no work zsh config found"
else
  source $HOME/.work-zshrc
fi

SPACESHIP_DOCKER_SHOW=false
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_CHAR_SYMBOL="λ "

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

autoload -U promptinit; promptinit
prompt spaceship


alias v="nvim"

# Dotfiles utility functions
# If simply titan is called go to titan directory
# If called with apply then run ./bin/run.sh
titan() {
  if [ "$1" = "apply" ]; then
    pwd=$(pwd)
    cd ~/titan
    sh ./bin/run.sh
    cd "${pwd}"
  elif [ "$1" = "edit" ]; then
    cd ~/titan && v
  else
    cd ~/titan
  fi
}
