format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $hg_branch\
  $package\
  $golang\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $terraform\
  $kubernetes\
  $memory_usage\
  $aws\
  $env_var\
  $cmd_duration\
  $line_break\
  $jobs\
  $time\
  $character\
"""


[git_branch]
symbol = " "
style = "bold red"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold yellow)"
vicmd_symbol = " "

[aws]
disabled = true

[nodejs]
symbol = " "

[package]
disabled = true

[kubernetes]
format = "within "
disabled = true
symbol = " "
