format = """\
  $character\
  $directory\
"""

[git_branch]
symbol = " "
style = "red"
format = "[$symbol $branch]($style) "

[directory]
style = "italic cyan"
format = "[$path]($style) > "

[character]
success_symbol = "[ ](green)"
error_symbol = "[ ](yellow)"
vicmd_symbol = "[ ](green)"

[aws]
disabled = true

[package]
disabled = true
