format = """\
  $jobs\
  $hostname\
  $directory\
  $git_branch\
  $git_status\
  $line_break\
  $character\
"""

[hostname]
ssh_symbol = "鷺"
format = "bold bright-yellow"

[git_branch]
symbol = " "
style = "purple"
format = "on [$symbol$branch]($style) "

[directory]
style = "italic cyan"
format = "[$path]($style) "

[character]
success_symbol = "[ ](green)"
error_symbol = "[ ](yellow)"
vicmd_symbol = "[ ](green)"

[aws]
disabled = true

[package]
disabled = true

[jobs]
symbol = " "
style = "bold bright-black"
