plugins=(
  git
  docker
  tmuxinator
  mix
  taskwarrior
  history-substring-search
  vi-mode
)

source $ZSH/oh-my-zsh.sh

alias v="nvim"
alias aqua="Asciiquarium"

# Task warrior tooling
alias t="task"
alias tap="task context personal"
alias taw="task context work"
alias chore="task add +personal +chore" 
alias d="delta"
alias l="hledger"
alias lworth="hledger bs --tree -2 --real -V"
alias ltrue="hledger balance --tree --real --empty"
alias lbalance="hledger balance --tree --auto --empty"
alias ledit="v $LEDGER_FILE"

# use exa for ls
alias ls='exa -al --icons --color=always --group-directories-first'
alias la='exa -a --icons --color=always --group-directories-first'
alias ll='exa -l --icons --color=always --group-directories-first'
alias lt='exa -aT --icons --color=always --group-directories-first'
alias titan='sudo salt-call state.apply'


tickle () {
    task $@ modify wait:soww
}

work () {
  if [ $# -eq 0 ]; then
    # are we in the work context?
    local context=$(task _get rc.context)
    echo $context
    if [ -z "${context}" ] && [ "${context}" = "work" ]; then
      task
    else
      task +work
    fi
  else
    task add +work $@
  fi
}

delta() {
  if [ "$1" = "launch" ]; then
    tmuxinator start $2
  fi
  
  if [ "$1" = "l" ]; then
    tmuxinator start $2
  fi

  if [ "$1" = "new" ]; then
    tmuxinator start launch name=${PWD##*/} root=$(pwd)
  fi
}

bench() {
  dir="$HOME/Documents/Wolf/bench.md"
  if [ $# -eq 0 ]
  then
    while read line
      do
        echo "$line" >> $dir
      done < "${1:-/dev/stdin}"
  else
    echo $@ >> $dir
  fi

}

title="A NEW BATTLE AWAITS, GUARDIAN"
printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
eval "$(direnv hook zsh)"

gpgconf --launch gpg-agent
eval "$(starship init zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/orlando/google-cloud-sdk/path.zsh.inc' ]; then . '/home/orlando/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/orlando/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/orlando/google-cloud-sdk/completion.zsh.inc'; fi
