# Path to your oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"
export PATH="$GOPATH/bin:"$HOME"/.local/bin:"$HOME"/.cargo/bin:$PATH"
export EDITOR="nvim"
export GOPATH=$HOME/go

export ERL_AFLAGS="-kernel shell_history enabled"

# Configurationh for prompt
if [ -f ~/zsh/promptrc ]; then
    source ~/zsh/promptrc
fi

# Configuration for path variable (varies between mac and arch)
if [ -f ~/zsh/pathrc ]; then
    source ~/zsh/pathrc
fi

source $ZSH/oh-my-zsh.sh

alias v="nvim"
alias aqua="Asciiquarium"

# Task warrior tooling
alias ta="task"
alias tap="task context personal"
alias taw="task context work"
alias in='task add +in'
alias d='delta'

tickle () {
    task $@ modify wait:soww
}

delta() {
  if [ "$1" = "launch" ]; then
    tmuxinator start $2
  fi
  
  if [ "$1" = "l" ]; then
    tmuxinator start $2
  fi

  if [ "$1" = "new" ]; then
    tmuxinator start launch name=${PWD##*/} root=$(pwd)
  fi
}

launch() {
  session_name=$(ls ~/Development | sk) 
  tmux attach -t $session_name > 2/dev/null || tmuxinator start launch name=$session_name root=~/Development/$session_name
}

title="A NEW BATTLE AWAITS, GUARDIAN"
printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"

# This is something for git so that certain commands know what branch to go against
export REVIEW_BASE=master
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
eval "$(direnv hook zsh)"

