# Configurationh for prompt
if [ -f $ZDOTDIR/promptrc ]; then
    source $ZDOTDIR/promptrc
fi

# Configuration for path variable (varies between mac and arch)
if [ -f $ZDOTDIR/pathrc ]; then
    source $ZDOTDIR/pathrc
fi

source $ZSH/oh-my-zsh.sh

alias v="nvim"
alias aqua="Asciiquarium"

# Task warrior tooling
alias t="task"
alias tap="task context personal"
alias taw="task context work"
alias in="task add +in"
alias chore="task add +personal +chore" 
alias d="delta"
alias l="hledger"
alias lworth="hledger bs --tree -2 --real -V"
alias ltrue="hledger balance --tree --real --empty"
alias lbalance="hledger balance --tree --auto --empty"
alias ledit="v $LEDGER_FILE"

tickle () {
    task $@ modify wait:soww
}

delta() {
  if [ "$1" = "launch" ]; then
    tmuxinator start $2
  fi
  
  if [ "$1" = "l" ]; then
    tmuxinator start $2
  fi

  if [ "$1" = "new" ]; then
    tmuxinator start launch name=${PWD##*/} root=$(pwd)
  fi
}

launch() {
  session_name=$(ls ~/Development | sk) 
  tmuxinator start $session_name 2>/dev/null || tmuxinator start launch name=$session_name root=~/Development/$session_name
}

title="A NEW BATTLE AWAITS, GUARDIAN"
printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
eval "$(direnv hook zsh)"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/orlando/google-cloud-sdk/path.zsh.inc' ]; then . '/home/orlando/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/orlando/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/orlando/google-cloud-sdk/completion.zsh.inc'; fi
