xdg_config_home: /home/orlando/.config
xdg_data_home: /home/orlando/.local/share
xdg_cache_home: /home/orlando/.cache
xdg_desktop_dir: /home/orlando/Desktop
xdg_documents_dir: /home/orlando/Documents
xdg_download_dir: /home/orlando/Downloads
xdg_music_dir: /home/orlando/Music
xdg_pictures_dir: /home/orlando/Pictures
xdg_publicshare_dir: /home/orlando/Public
xdg_templates_dir: /home/orlando/Templates
xdg_videos_dir: /home/orlando/Videos
